os: linux
dist: xenial
git:
  depth: 1
language: go
go: "1.13"
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: "Linting"
      script: ./mage -v lint:go
    - stage: "Build"
      script: ./mage -v build:docker

