os: linux
dist: trusty
sudo: false
git:
  depth: 1
language: node_js
node_js:
  - "10.4.1"
before_install: .bin/install_hugo.sh
script: npm run ci
cache:
  directories:
    - .vendor
    - node_modules

