os: linux
dist: xenial
git:
  depth: 1
language: go
go:
  - "1.13"
env:
  - GO111MODULE=on
before_install:
  - .mage/compile
jobs:
  include:
    - stage: "Linting"
      script: ./mage -v lint:go
    - stage: "Content generation"
      name: "Go packages"
      script: ./mage -v gen:gopkgs
    - name: "Projects"
      script: ./mage -v gen:projects
    - stage: "Build"
      script: ./mage -v docker:build

