baseURL: https://www.ntrrg.dev/
title: ntrrg
params:
  name: ntrrg
  title: ntrrg
  titleSeparator: "-"
  copyright: Miguel Angel Rivera Notararigo 2020
  author:
    type: Person
    name: Miguel Angel Rivera Notararigo
    email: ntrrgx@gmail.com
    website: https://ntrrg.dev/
  image: /favicon-512x512.png
  ampImage: /icon-206x60.png
  articleTypes:
    - blog
    - series
  searchIndexTypes:
    - blog
    - challenges
    - projects
    - series
  relatedCount: 5
  #googleTagManager: GTM-NZ2R3W7
  #disqus: ntweb
  interledger: "$ilp.uphold.com/YM4XLxrdPh44"
  goPlayground: https://play.golang.org
  projects:
    - https://github.com/ntrrg/docker-hugo
    - https://github.com/ntrrg/ntgo
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: I am Miguel Angel, just another developer working hard to not be just another developer.
      menu:
        items:
          - url: "/blog/"
          - url: "/projects/"
          - url: "/challenges/"
          - url: "https://www.instagram.com/ntrrg/"
            text: "Gallery"
        beforeEach: "| "
      secondaryMenu:
        items:
          - url: "/settings/"
        beforeEach: "["
        afterEach: "]"
      footerMenu:
        items:
          - url: "/pay/"
        beforeEach: "["
        afterEach: "] "
  es:
    languageName: Español
    params:
      description: Soy Miguel Angel, solo otro desarrollador más trabajando duro para no ser solo otro desarrollador más.
      menu:
        items:
          - url: "/blog/"
          - url: "/projects/"
          - url: "https://www.instagram.com/ntrrg/"
            text: "Galería"
        beforeEach: "| "
      secondaryMenu:
        items:
          - url: "/settings/"
        beforeEach: "["
        afterEach: "]"
      footerMenu:
        items:
          - url: "/pay/"
        beforeEach: "["
        afterEach: "] "
taxonomies:
  serie: series
  tag: tags
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 50
  threshold: 100
  toLower: false
permalinks:
  blog: /:sections/:slug/
  projects: /:sections/:slug/
theme: []
Paginate: 10
enableEmoji: true
markup:
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2
  tableOfContents:
    startLevel: 1
    endLevel: 6
  goldmark:
    renderer:
      unsafe: true
enableRobotsTXT: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
    - JSON
  term:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON
ignoreErrors: 
  - error-remote-getjson
enableGitInfo: true
minify: true
server:
  headers:
    - for: /**
      values:
        Cache-Control: no-cache, no-store
        X-Content-Type-Options: nosniff
        Referrer-Policy: strict-origin-when-cross-origin
    - for: /**/
      values:
        X-XSS-Protection: 1; mode=block
    - for: /*.html
      values:
        X-XSS-Protection: 1; mode=block
    - for: /*.webmanifest
      values:
        Content-Type: application/manifest+json; charset=utf-8

