baseURL: https://nt.web.ve/
title: NtWeb
copyright: Copyright © 2018 Miguel Angel Rivera Notararigo
enableRobotsTXT: true
params:
  author:
    id: ntrrg
    name: Miguel Angel Rivera Notararigo
    email: ntrrgx@gmail.com
  image: images/logo.png
  social:
    - name: GitHub (@ntrrg)
      url: https://github.com/ntrrg
    - name: Gmail (ntrrgx@gmail.com)
      url: mailto://ntrrgx@gmail.com
    - name: LinkedIn (ntrrg)
      url: https://www.linkedin.com/in/ntrrg
    - name: Telegram (@ntrrg)
      url: https://t.me/ntrrg
  goPlayground: https://play.golang.org
permalinks:
  blog: /:sections/:slug/

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

