baseURL: https://nt.web.ve/
enableRobotsTXT: true
params:
  title: ntrrg
  titleSeparator: ·
  org:
    id: ntrrg
    name: Miguel Angel Rivera Notararigo
    image: uploads/logo.png
    vimage: uploads/isologo.png
    social:
      github:
        text: GitHub (@ntrrg)
        url: https://github.com/ntrrg
        icon: fab fa-github
        weight: 1
      linkedin:
        text: LinkedIn (ntrrg)
        url: https://www.linkedin.com/in/ntrrg
        icon: fab fa-linkedin
        weight: 2
      telegram:
        text: Telegram (@ntrrg)
        url: https://t.me/ntrrg
        icon: fab fa-telegram
        weight: 3
      email:
        text: ntrrgx@gmail.com
        url: mailto://ntrrgx@gmail.com
        icon: fab fa-google
        weight: 4
      phone:
        text: +58 424-7484276
        url: tel://584247484276
        icon: fa fa-phone-square
        weight: 5
  googleTagManager: GTM-NZ2R3W7
  disqus: ntweb
  goPlayground: https://play.golang.org
permalinks:
  blog: /:sections/:slug/
taxonomies:
  serie: series
  tag: tags
  category: categories
  kind: kinds
  tech: techs
pygmentsCodeFences: true
pygmentsUseClasses: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

