baseURL: https://nt.web.ve/
enableRobotsTXT: true
params:
  title: ntrrg
  titleSeparator: ·
  image: images/logo.png
  vimage: images/isologo.png
  org:
    id: ntrrg
    name: Miguel Angel Rivera Notararigo
    website: https://nt.web.ve
    contact:
      github:
        text: GitHub (@ntrrg)
        url: https://github.com/ntrrg
        icon: fab fa-github
        weight: 1
      linkedin:
        text: LinkedIn (ntrrg)
        url: https://www.linkedin.com/in/ntrrg
        icon: fab fa-linkedin
        weight: 2
      telegram:
        text: Telegram (@ntrrg)
        url: https://t.me/ntrrg
        icon: fab fa-telegram
        weight: 3
      email:
        text: ntrrgx@gmail.com
        url: mailto://ntrrgx@gmail.com
        icon: fab fa-google
        weight: 4
      google-fi:
        text: 5203130363@msg.fi.google.com
        url: mailto://5203130363@msg.fi.google.com
        icon: fab fa-google
        weight: 5
      phone-us:
        text: +1 520-313-0363
        url: tel://+15203130363
        icon: fa fa-phone-square
        weight: 6
      phone-ve:
        text: +58 424-7484276
        url: tel://+584247484276
        icon: fa fa-phone-square
        weight: 7
  googleTagManager: GTM-NZ2R3W7
  disqus: ntweb
  goPlayground: https://play.golang.org
  projects:
    - https://github.com/ntrrg/ntdocutils
    - https://github.com/ntrrg/ntgo
  goPackages:
    - https://github.com/ntrrg/ntgo
permalinks:
  blog: /:sections/:slug/
taxonomies:
  serie: series
  tag: tags
  category: categories
  kind: kinds
  tech: techs
pygmentsCodeFences: true
pygmentsUseClasses: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

