baseURL: https://nt.web.ve/
permalinks:
  blog: /:sections/:slug/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
taxonomies:
  tag: tags
  serie: series
Paginate: 10
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
    - RSS
  page:
    - HTML
pygmentsCodeFences: true
pygmentsUseClasses: true
enableRobotsTXT: true
params:
  name: ntrrg
  title: ntrrg
  titleSeparator: ☮
  author: ntrrg
  singleAuthor: true
  image: images/logo.png
  ampImage: images/isologo-amp.png
  # googleTagManager: GTM-NZ2R3W7
  disqus: ntweb
  goPlayground: https://play.golang.org
  projects:
    - https://github.com/ntrrg/docker-hugo
    - https://github.com/ntrrg/ntdocutils
    - https://github.com/ntrrg/ntgo
    - https://github.com/ntrrg/pish
  goPackages:
    - https://github.com/ntrrg/ntgo
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

