baseURL: https://nt.web.ve/
permalinks:
  blog: /:sections/:slug/
  gallery: /:sections/:slug/
taxonomies:
  tag: tags
  serie: series
Paginate: 10
markup:
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
    - JSON
  taxonomyTerm:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON
enableRobotsTXT: true
params:
  name: ntrrg
  title: ntrrg
  titleSeparator: ☮
  author: ntrrg
  singleAuthor: true
  image: images/logo.png
  ampImage: images/isologo-amp.png
  # googleTagManager: GTM-NZ2R3W7
  disqus: ntweb
  goPlayground: https://play.golang.org
  projects:
    - https://github.com/ntrrg/pish
    - https://github.com/ntrrg/docker-hugo
    - https://github.com/ntrrg/ntgo
    - https://github.com/ntrrg/sdb
    - https://github.com/ntrrg/usersd
  goPackages:
    - https://github.com/ntrrg/ntgo
    - https://github.com/ntrrg/sdb
    - https://github.com/ntrrg/usersd
  menu:
    - url: "/blog"
    - url: "/projects"
    - url: "/gallery"
    - url: "/settings"
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

