baseURL: https://nt.web.ve/
title: NtWeb
copyright: Copyright © 2018 Miguel Angel Rivera Notararigo
enableRobotsTXT: true
params:
  author:
    id: ntrrg
    name: Miguel Angel Rivera Notararigo
    email: ntrrgx@gmail.com
  image: images/logo.png
  social:
    - name: Telegram
      weight: 1
      url: https://t.me/ntrrg
    - name: GitHub
      weight: 2
      url: https://github.com/ntrrg
    - name: LinkedIn
      weight: 3
      url: https://www.linkedin.com/in/ntrrg
permalinks:
  blog: /:sections/:slug/

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small site with great intentions.
  es:
    languageName: Español
    params:
      description: Un pequeño sitio web con grandes intenciones.

