[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "hugo -DEF --baseURL=/"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "origin-when-cross-origin"

[[redirects]]
  from = "https://www.nt.web.ve/*"
  to = "https://nt.web.ve/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.nt.web.ve/*"
  to = "https://nt.web.ve/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ntweb.netlify.com/*"
  to = "https://nt.web.ve/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404.html"
  status = 404

