[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.40.3"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "origin-when-cross-origin"

