backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: blog
    label: Articles
    folder: content/blog
    create: true
    slug: {{slug}}
    fields:
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Image
        name: image
        widget: image
        required: false
      - label: Categories
        name: categories
        widget: text
        default: []
      - label: Tags
        name: tags
        widget: text
        default: []
      - label: Body
        name: body
        widget: markdown

