---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Articles
  create: all
  match: "**/*"
  exclude: "**/_*"
  templates:
  - blog
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  exclude: "**/_*"
  templates:
  - projects
- type: heading
  label: Data
- type: document
  path: config.yaml
  label: Parameters
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
