name: Docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Log into the Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: "Build and push 'latest'"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: "Build and push 'editing'"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker build -t $DOCKER_IMAGE:editing -f editing.Dockerfile .
          docker push $DOCKER_IMAGE:editing

      - name: "Build and push image from pull request"
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          docker build -t $DOCKER_IMAGE:preview-$GITHUB_REF .
          docker push $DOCKER_IMAGE:preview-$GITHUB_REF

